# Copyright (c) The Amphitheatre Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.8"

[buildpack]
  description = "A Cloud Native Buildpack with an order definition suitable for Aleo applications"
  homepage = "https://github.com/amp-buildpacks/leo"
  id = "amp-buildpacks/leo"
  keywords = ["Leo", "Aleo"]
  name = "AMP Buildpack for Leo"
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/amp-buildpacks/leo/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "README.md", "buildpack.toml"]

[[order]]

  [[order.group]]
    id = "amp-buildpacks/leo-dist"
    version = "0.1.18"

  [[order.group]]
    id = "amp-buildpacks/aleo"
    version = "0.2.0"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.9.0"
