description = "A sample Builder for using Leo related CNBs"

[[buildpacks]]
  id = "amp-buildpacks/leo-dist"
  uri = "docker://ghcr.io/amp-buildpacks/leo-dist:0.1.0"

[[buildpacks]]
  id = "amp-buildpacks/aleo"
  uri = "docker://ghcr.io/amp-buildpacks/aleo:0.1.0"

[[buildpacks]]
  id = "paketo-buildpacks/procfile"
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.6.8"

[[order]]
  [[order.group]]
    id = "amp-buildpacks/leo-dist"

  [[order.group]]
    id = "amp-buildpacks/aleo"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true

[stack]
  id = "io.buildpacks.stacks.jammy.tiny"
  build-image = "docker.io/paketobuildpacks/build-jammy-tiny"
  run-image = "docker.io/paketobuildpacks/run-jammy-tiny"
